version: "3.8"

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - mongodb
    volumes:
      - /Users/nghiadoan/Database/LearnWMe/mongodb:/data/db
  mongodb_express_container:
      image: mongo-express
      environment:
        ME_CONFIG_MONGODB_SERVER: mongodb_container
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: password
      depends_on:
        - mongodb_container
      ports:
        - 8081:8081
      networks:
        - mongodb
networks:
  mongodb:
    name: mongodb

